pull_request_rules:
  - name: automatic merge on CI success require review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: automatic merge on CI success for TemplateControl
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - label=merge-when-green
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
